In [1]:
import cv2
import numpy as np
import glob
import os 
 


In [26]:
path_of_the_directory= '/Users/mohamedbasuony/Desktop/Research/create videos'
x=0
y=[]
for foldername in os.listdir(path_of_the_directory):
    folder = os.path.join(path_of_the_directory, foldername)
    img_array = []
    print(folder)
    if folder == os.path.join(path_of_the_directory, ".DS_Store"):
        print("here?")
        os.remove(folder)
        continue
    for filename in os.listdir(folder):
        
        f= os.path.join(folder, filename)
        print(f)
        if f == os.path.join(folder, ".DS_Store"):
            print("here?")
            continue
        img = cv2.imread(f)
        print(img)
        height, width, layers = img.shape
        size = (width,height)
        img_array.append(img)
        x=x+1
    out = cv2.VideoWriter(f"{folder}.avi", 
                         cv2.VideoWriter_fourcc(*'MJPG'),
                         10, size)
    y.append(x)
    x=0
    for i in range(len(img_array)):
        out.write(img_array[i])
    out.release()
print(y)

/Users/mohamedbasuony/Desktop/Research/create videos/236_1_Northwind_video
/Users/mohamedbasuony/Desktop/Research/create videos/236_1_Northwind_video/360.png
[[[ 43  35  37]
  [ 45  39  42]
  [ 65  59  62]
  ...
  [ 10  10  10]
  [ 13  13  13]
  [ 14  18  20]]

 [[ 39  31  31]
  [ 42  37  38]
  [ 73  68  69]
  ...
  [ 10  10  10]
  [ 12  12  12]
  [ 14  16  18]]

 [[ 40  35  36]
  [ 76  71  72]
  [ 82  79  80]
  ...
  [  9   9   9]
  [ 10  10  10]
  [ 14  16  18]]

 ...

 [[161 241 255]
  [161 239 255]
  [158 236 255]
  ...
  [ 78 151 183]
  [ 82 155 187]
  [ 84 154 188]]

 [[160 240 255]
  [159 237 255]
  [157 235 255]
  ...
  [ 81 154 186]
  [ 82 155 187]
  [ 86 156 190]]

 [[161 238 255]
  [157 234 255]
  [155 232 255]
  ...
  [ 85 156 188]
  [ 86 157 189]
  [ 90 158 191]]]
/Users/mohamedbasuony/Desktop/Research/create videos/236_1_Northwind_video/610.png
[[[ 22  23  28]
  [ 20  23  28]
  [ 19  22  27]
  ...
  [  4   0   3]
  [  5   0   6]
  [  5   0   6]]

 [[ 21  22  27]
  [ 19  2

[[[ 73  73  73]
  [ 66  66  66]
  [ 65  64  66]
  ...
  [ 32  36  45]
  [ 39  43  52]
  [ 40  44  53]]

 [[ 67  67  67]
  [ 64  64  64]
  [ 65  64  66]
  ...
  [ 34  36  43]
  [ 41  43  50]
  [ 40  45  51]]

 [[ 65  64  66]
  [ 64  63  65]
  [ 65  64  66]
  ...
  [ 34  36  43]
  [ 40  42  49]
  [ 45  50  56]]

 ...

 [[152 230 252]
  [146 221 246]
  [142 217 242]
  ...
  [ 21  89 130]
  [ 30  98 139]
  [ 38 106 147]]

 [[153 231 253]
  [146 223 248]
  [140 217 242]
  ...
  [ 23  91 132]
  [ 29  97 138]
  [ 38 106 147]]

 [[153 231 253]
  [146 223 248]
  [143 220 245]
  ...
  [ 25  93 134]
  [ 25  93 134]
  [ 36 104 145]]]
/Users/mohamedbasuony/Desktop/Research/create videos/236_1_Northwind_video/850.png
[[[ 37  40  40]
  [ 33  36  36]
  [ 28  30  32]
  ...
  [  4   0   3]
  [  2   1   3]
  [  3   2   4]]

 [[ 36  39  39]
  [ 31  34  34]
  [ 28  30  32]
  ...
  [  3   0   2]
  [  0   0   2]
  [  0   1   3]]

 [[ 31  34  34]
  [ 30  33  33]
  [ 27  29  31]
  ...
  [  4   0   3]
  [  0   

[[[ 15  17  24]
  [ 16  17  22]
  [ 16  17  22]
  ...
  [  5   0   6]
  [  5   0   6]
  [  5   0   6]]

 [[ 14  16  23]
  [ 16  17  22]
  [ 16  17  22]
  ...
  [  6   0   5]
  [  7   0   6]
  [  7   0   6]]

 [[ 10  17  23]
  [ 11  18  24]
  [ 11  18  24]
  ...
  [  7   0   6]
  [  7   0   6]
  [  7   0   6]]

 ...

 [[151 227 255]
  [150 226 255]
  [146 220 254]
  ...
  [ 60 130 164]
  [ 63 133 167]
  [ 65 136 168]]

 [[151 227 255]
  [148 224 253]
  [146 220 254]
  ...
  [ 60 132 166]
  [ 63 135 169]
  [ 67 138 170]]

 [[152 227 254]
  [149 224 251]
  [146 222 251]
  ...
  [ 62 134 168]
  [ 64 136 170]
  [ 69 140 172]]]
/Users/mohamedbasuony/Desktop/Research/create videos/236_1_Northwind_video/780.png
[[[ 23  20  27]
  [ 24  19  25]
  [ 24  19  25]
  ...
  [  0   3   5]
  [  0   3   5]
  [  1   3   5]]

 [[ 25  22  29]
  [ 24  22  27]
  [ 22  20  25]
  ...
  [  0   3   5]
  [  0   3   5]
  [  1   3   5]]

 [[ 25  22  29]
  [ 24  22  27]
  [ 22  20  25]
  ...
  [  0   3   5]
  [  0   

[[[118 126 135]
  [117 125 134]
  [115 126 134]
  ...
  [105 127 161]
  [105 127 161]
  [105 127 161]]

 [[118 126 135]
  [118 126 135]
  [117 128 136]
  ...
  [103 128 161]
  [103 128 161]
  [103 128 161]]

 [[119 127 136]
  [120 128 137]
  [118 129 137]
  ...
  [103 128 161]
  [103 128 161]
  [103 128 161]]

 ...

 [[ 60  49 122]
  [ 65  54 127]
  [ 70  58 135]
  ...
  [ 70  65 140]
  [ 72  67 142]
  [ 74  67 142]]

 [[ 63  52 125]
  [ 69  58 131]
  [ 76  64 141]
  ...
  [ 73  63 139]
  [ 75  65 141]
  [ 76  66 142]]

 [[ 68  57 130]
  [ 74  63 136]
  [ 80  68 145]
  ...
  [ 73  63 139]
  [ 75  65 141]
  [ 76  66 142]]]
/Users/mohamedbasuony/Desktop/Research/create videos/233_1_Northwind_video/510.png
[[[147 160 188]
  [147 160 188]
  [145 161 188]
  ...
  [106 128 164]
  [107 129 163]
  [107 129 163]]

 [[147 160 188]
  [147 160 188]
  [145 161 188]
  ...
  [104 129 164]
  [108 128 164]
  [108 128 164]]

 [[149 162 190]
  [147 160 188]
  [146 159 187]
  ...
  [104 129 164]
  [108 12

[[[150 164 190]
  [150 164 190]
  [151 165 191]
  ...
  [108 128 162]
  [108 128 162]
  [108 128 162]]

 [[150 164 190]
  [150 164 190]
  [148 165 190]
  ...
  [108 128 162]
  [108 128 162]
  [108 128 162]]

 [[149 163 189]
  [149 163 189]
  [147 164 189]
  ...
  [109 127 163]
  [110 128 164]
  [111 129 165]]

 ...

 [[105  92 163]
  [104  87 170]
  [103  86 169]
  ...
  [ 82  63 140]
  [ 83  64 141]
  [ 83  65 139]]

 [[104  91 162]
  [105  88 171]
  [103  86 169]
  ...
  [ 80  63 140]
  [ 80  63 140]
  [ 81  64 141]]

 [[102  92 162]
  [103  87 176]
  [102  86 175]
  ...
  [ 80  63 140]
  [ 81  64 141]
  [ 82  65 142]]]
/Users/mohamedbasuony/Desktop/Research/create videos/233_1_Northwind_video/1100.png
[[[153 163 189]
  [149 163 189]
  [150 164 190]
  ...
  [111 129 163]
  [106 128 162]
  [106 128 162]]

 [[158 163 190]
  [149 163 189]
  [150 164 190]
  ...
  [112 130 164]
  [105 127 161]
  [105 127 161]]

 [[158 163 190]
  [149 163 189]
  [149 163 189]
  ...
  [112 130 164]
  [105 1

[[[130 141 164]
  [135 146 169]
  [136 146 172]
  ...
  [102 125 156]
  [100 126 156]
  [100 126 156]]

 [[132 143 164]
  [136 147 168]
  [137 149 175]
  ...
  [102 125 156]
  [102 125 156]
  [102 125 156]]

 [[132 143 164]
  [136 147 168]
  [137 149 175]
  ...
  [102 125 156]
  [102 125 156]
  [102 125 156]]

 ...

 [[105  85 166]
  [103  83 164]
  [ 99  81 162]
  ...
  [ 70  58 134]
  [ 68  58 134]
  [ 68  58 134]]

 [[107  87 168]
  [104  84 165]
  [100  82 163]
  ...
  [ 73  56 133]
  [ 72  57 134]
  [ 72  57 134]]

 [[105  87 168]
  [102  84 165]
  [ 98  82 163]
  ...
  [ 72  55 132]
  [ 70  55 132]
  [ 72  57 134]]]
/Users/mohamedbasuony/Desktop/Research/create videos/233_1_Northwind_video/1000.png
[[[122 128 152]
  [108 114 138]
  [ 78  84 108]
  ...
  [112 131 162]
  [112 131 162]
  [113 132 163]]

 [[115 121 145]
  [ 90  96 120]
  [ 60  66  90]
  ...
  [112 131 162]
  [112 131 162]
  [113 132 163]]

 [[109 115 139]
  [ 62  68  92]
  [ 44  50  72]
  ...
  [112 131 162]
  [112 1

[[[203 197 200]
  [200 194 197]
  [197 191 194]
  ...
  [171 173 175]
  [171 173 175]
  [171 173 175]]

 [[203 197 200]
  [199 193 196]
  [197 191 194]
  ...
  [171 173 175]
  [171 173 175]
  [170 172 174]]

 [[201 194 200]
  [197 190 196]
  [197 190 196]
  ...
  [172 174 176]
  [171 173 175]
  [171 173 175]]

 ...

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  2   2   2]
  [  3   3   3]
  [  4   3   5]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  1   1   1]
  [  2   2   2]
  [  1   0   2]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  1   1   1]
  [  1   0   2]]]
/Users/mohamedbasuony/Desktop/Research/create videos/215_2_Northwind_video/370.png
[[[197 195 200]
  [195 193 198]
  [196 191 197]
  ...
  [174 172 177]
  [174 172 177]
  [174 172 177]]

 [[190 189 191]
  [187 186 188]
  [191 186 192]
  ...
  [174 171 178]
  [175 169 177]
  [175 169 177]]

 [[187 186 188]
  [182 181 183]
  [176 171 177]
  ...
  [173 170 177]
  [174 16

[[[203 196 202]
  [197 196 198]
  [197 195 200]
  ...
  [178 176 181]
  [179 177 182]
  [179 177 182]]

 [[201 194 200]
  [197 196 198]
  [197 196 198]
  ...
  [180 175 181]
  [179 177 182]
  [179 177 182]]

 [[199 194 200]
  [197 196 198]
  [200 199 201]
  ...
  [181 176 182]
  [179 177 182]
  [179 177 182]]

 ...

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [101 100  89]
  [ 84  83  72]
  [ 66  65  54]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [ 72  71  44]
  [ 66  65  38]
  [ 68  68  39]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [ 72  71  44]
  [ 67  66  39]
  [ 69  69  40]]]
/Users/mohamedbasuony/Desktop/Research/create videos/215_2_Northwind_video/1110.png
[[[192 187 193]
  [187 187 194]
  [193 193 200]
  ...
  [175 170 176]
  [175 170 176]
  [175 170 176]]

 [[194 189 195]
  [192 189 196]
  [194 191 198]
  ...
  [174 169 175]
  [174 169 175]
  [174 168 176]]

 [[196 191 197]
  [193 190 197]
  [193 190 197]
  ...
  [174 169 175]
  [174 1

[[[203 195 203]
  [193 194 199]
  [190 191 196]
  ...
  [179 178 180]
  [179 178 180]
  [178 177 179]]

 [[215 210 216]
  [190 196 200]
  [185 191 195]
  ...
  [179 178 180]
  [179 178 180]
  [178 177 179]]

 [[204 199 205]
  [216 211 217]
  [192 198 202]
  ...
  [179 178 180]
  [179 178 180]
  [178 177 179]]

 ...

 [[  3   2   4]
  [  3   2   4]
  [  2   1   3]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  3   2   4]
  [  3   2   4]
  [  2   1   3]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  3   2   4]
  [  3   2   4]
  [  2   1   3]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]]
/Users/mohamedbasuony/Desktop/Research/create videos/215_2_Northwind_video/1600.png
[[[199 193 196]
  [199 193 196]
  [199 194 195]
  ...
  [177 174 175]
  [177 174 175]
  [178 174 177]]

 [[195 194 196]
  [195 194 196]
  [195 195 195]
  ...
  [178 173 172]
  [178 173 172]
  [180 175 176]]

 [[195 194 196]
  [195 194 196]
  [197 197 197]
  ...
  [178 173 172]
  [178 1

[[[  3  21  28]
  [ 67  85  92]
  [ 84 105 109]
  ...
  [ 36  61  62]
  [  0  13  14]
  [ 26  45  44]]

 [[  0  17  24]
  [ 60  78  85]
  [ 93 114 118]
  ...
  [ 50  72  74]
  [  0  18  20]
  [ 22  43  42]]

 [[  0  15  22]
  [ 66  84  91]
  [ 87 108 112]
  ...
  [ 53  75  77]
  [ 10  32  34]
  [ 18  39  38]]

 ...

 [[  0  24  34]
  [  0  23  33]
  [  0  24  33]
  ...
  [  0  16  30]
  [  1  19  33]
  [  1  22  35]]

 [[  0  24  34]
  [  0  24  34]
  [  0  24  36]
  ...
  [  0  16  30]
  [  1  19  33]
  [  1  22  35]]

 [[  0  23  33]
  [  0  22  32]
  [  0  24  36]
  ...
  [  0  16  30]
  [  1  19  33]
  [  1  22  35]]]
/Users/mohamedbasuony/Desktop/Research/create videos/312_2_Freeform_video/210.png
[[[ 50  53  64]
  [ 64  71  84]
  [ 43  50  63]
  ...
  [194 198 193]
  [194 199 192]
  [194 199 192]]

 [[ 60  63  76]
  [ 65  75  87]
  [ 46  56  68]
  ...
  [194 199 192]
  [194 199 192]
  [194 199 192]]

 [[ 64  67  80]
  [ 61  71  83]
  [ 41  51  63]
  ...
  [191 196 189]
  [192 197

[[[  6  24  31]
  [ 97 115 122]
  [127 150 156]
  ...
  [191 200 188]
  [191 199 189]
  [191 199 189]]

 [[ 29  47  54]
  [113 131 138]
  [127 150 156]
  ...
  [191 200 188]
  [191 199 189]
  [191 199 189]]

 [[ 47  64  73]
  [113 130 139]
  [125 149 157]
  ...
  [190 199 187]
  [190 198 188]
  [191 199 189]]

 ...

 [[  4  28  45]
  [  0  20  37]
  [  0  15  31]
  ...
  [  3  25  35]
  [  5  24  35]
  [  5  24  35]]

 [[  3  29  46]
  [  0  19  36]
  [  0  15  33]
  ...
  [  3  24  37]
  [  6  24  38]
  [  4  22  36]]

 [[  1  27  44]
  [  0  20  37]
  [  0  15  33]
  ...
  [  6  27  40]
  [  8  26  40]
  [  5  23  37]]]
/Users/mohamedbasuony/Desktop/Research/create videos/312_2_Freeform_video/440.png
[[[ 28  31  36]
  [ 63  66  71]
  [ 70  77  83]
  ...
  [199 207 204]
  [202 207 205]
  [202 207 205]]

 [[ 20  23  28]
  [ 75  78  83]
  [ 43  50  56]
  ...
  [199 208 202]
  [202 207 205]
  [202 207 205]]

 [[  0   8  12]
  [ 72  80  84]
  [ 18  27  33]
  ...
  [196 205 199]
  [199 204

[[[251 237 235]
  [253 237 235]
  [255 239 237]
  ...
  [231 223 223]
  [231 223 223]
  [231 223 223]]

 [[251 237 235]
  [253 237 235]
  [255 239 237]
  ...
  [231 223 223]
  [231 223 223]
  [231 223 223]]

 [[251 237 235]
  [255 239 237]
  [255 240 238]
  ...
  [233 223 225]
  [233 223 225]
  [231 223 223]]

 ...

 [[150 143 140]
  [158 156 152]
  [ 74  72  68]
  ...
  [184 181 180]
  [183 180 179]
  [168 165 164]]

 [[125 128 126]
  [ 65  68  66]
  [  0   0   2]
  ...
  [187 184 183]
  [190 187 186]
  [174 171 170]]

 [[121 124 122]
  [ 42  45  43]
  [  0   0   2]
  ...
  [187 187 185]
  [190 190 188]
  [184 181 180]]]
/Users/mohamedbasuony/Desktop/Research/create videos/215_3_Freeform_video/370.png
[[[255 246 246]
  [254 244 244]
  [253 243 243]
  ...
  [212 203 207]
  [213 205 207]
  [217 209 211]]

 [[253 243 243]
  [254 244 244]
  [252 242 242]
  ...
  [208 199 203]
  [213 205 207]
  [215 207 209]]

 [[254 244 244]
  [254 244 244]
  [253 243 243]
  ...
  [197 191 194]
  [207 202

[[[ 96 119 132]
  [ 96 119 132]
  [ 94 120 132]
  ...
  [ 24  20  23]
  [ 29  23  26]
  [ 35  29  32]]

 [[ 97 120 133]
  [ 98 121 134]
  [ 95 121 133]
  ...
  [ 21  17  20]
  [ 19  21  23]
  [ 24  26  28]]

 [[ 99 121 136]
  [100 122 137]
  [ 96 123 137]
  ...
  [ 21  17  20]
  [ 16  18  20]
  [ 21  23  25]]

 ...

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  7   0   0]
  [  7   0   0]
  [  5   0   1]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  7   0   0]
  [  7   0   0]
  [  5   0   1]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  7   0   0]
  [  7   0   0]
  [  5   0   1]]]
/Users/mohamedbasuony/Desktop/Research/create videos/234_3_Freeform_video/170.png
[[[103 123 138]
  [105 120 136]
  [105 120 136]
  ...
  [ 19  16  23]
  [ 18  15  22]
  [ 19  16  23]]

 [[ 98 118 133]
  [100 115 131]
  [ 99 114 130]
  ...
  [ 21  15  23]
  [ 21  15  23]
  [ 21  15  23]]

 [[ 86 106 121]
  [ 87 104 120]
  [ 87 104 120]
  ...
  [ 21  15  23]
  [ 21  15

[[[ 33  68  79]
  [ 40  75  86]
  [ 45  87  97]
  ...
  [185 191 186]
  [185 191 186]
  [185 191 186]]

 [[ 60  98 108]
  [ 58  96 106]
  [ 48  90 100]
  ...
  [185 191 186]
  [185 191 186]
  [183 192 186]]

 [[ 95 133 143]
  [ 85 123 133]
  [ 61 103 113]
  ...
  [187 193 188]
  [185 191 186]
  [182 191 185]]

 ...

 [[ 71  99 111]
  [ 63  98 115]
  [ 61  96 113]
  ...
  [ 57  57  71]
  [ 79  66  80]
  [111  98 112]]

 [[ 69  97 109]
  [ 61  96 113]
  [ 60  95 112]
  ...
  [ 36  49  65]
  [ 22   8  27]
  [ 29  15  34]]

 [[ 68  96 108]
  [ 60  95 114]
  [ 59  94 113]
  ...
  [ 73  86 102]
  [ 30  16  35]
  [ 16   2  21]]]
/Users/mohamedbasuony/Desktop/Research/create videos/331_1_Northwind_video/1120.png
[[[  0  20  35]
  [ 11  31  46]
  [ 11  37  54]
  ...
  [189 193 188]
  [190 193 191]
  [190 193 191]]

 [[ 50  70  85]
  [ 27  47  62]
  [ 10  36  53]
  ...
  [189 193 188]
  [189 192 190]
  [190 193 191]]

 [[ 91 111 126]
  [ 28  48  63]
  [ 20  49  63]
  ...
  [187 191 186]
  [189 1

[[[209 206 205]
  [209 206 205]
  [209 206 205]
  ...
  [149 166 170]
  [149 166 170]
  [151 165 170]]

 [[209 206 205]
  [209 206 205]
  [209 206 205]
  ...
  [149 166 170]
  [151 165 170]
  [151 165 170]]

 [[209 206 205]
  [209 206 205]
  [209 206 205]
  ...
  [149 166 170]
  [151 165 170]
  [151 165 170]]

 ...

 [[ 11   3   5]
  [ 11   3   5]
  [ 11   3   5]
  ...
  [  1   1   0]
  [  2   2   0]
  [  1   1   0]]

 [[ 12   4   6]
  [ 12   4   6]
  [ 11   3   5]
  ...
  [  1   1   0]
  [  2   2   0]
  [  2   2   0]]

 [[ 11   3   5]
  [ 12   4   6]
  [ 12   4   6]
  ...
  [  1   1   0]
  [  2   2   0]
  [  2   2   0]]]
/Users/mohamedbasuony/Desktop/Research/create videos/310_4_Northwind_video/1020.png
[[[  9   4  18]
  [  3  10  11]
  [ 29  35  39]
  ...
  [132 152 159]
  [136 156 163]
  [142 160 167]]

 [[  5   0  14]
  [  0   6   7]
  [ 32  39  40]
  ...
  [133 153 160]
  [135 155 162]
  [141 159 166]]

 [[  3   0   9]
  [  1   9   6]
  [ 38  45  46]
  ...
  [136 156 163]
  [136 1

[[[206 203 202]
  [206 203 202]
  [206 203 202]
  ...
  [150 167 171]
  [150 167 171]
  [150 167 171]]

 [[205 202 201]
  [205 202 201]
  [205 202 201]
  ...
  [150 167 171]
  [150 167 171]
  [150 167 171]]

 [[205 202 201]
  [205 202 201]
  [205 202 201]
  ...
  [150 167 171]
  [150 167 171]
  [150 167 171]]

 ...

 [[  6   3   4]
  [  6   3   4]
  [  6   3   4]
  ...
  [150 150 148]
  [154 149 148]
  [154 149 148]]

 [[  5   2   3]
  [  5   2   3]
  [  5   2   3]
  ...
  [150 150 148]
  [154 149 148]
  [154 149 148]]

 [[  5   2   3]
  [  5   2   3]
  [  5   2   3]
  ...
  [154 149 148]
  [154 149 148]
  [154 149 148]]]
/Users/mohamedbasuony/Desktop/Research/create videos/310_4_Northwind_video/1160.png
[[[ 30  21  45]
  [ 15   6  30]
  [  8   2  26]
  ...
  [152 167 170]
  [150 165 168]
  [153 168 171]]

 [[ 25  16  40]
  [ 18   9  33]
  [ 19  13  37]
  ...
  [152 167 170]
  [156 171 174]
  [153 168 177]]

 [[ 22  13  37]
  [ 25  16  40]
  [ 31  23  45]
  ...
  [153 168 171]
  [157 1

[[[111 118 104]
  [111 118 104]
  [111 118 104]
  ...
  [ 57  69  40]
  [ 57  64  34]
  [ 57  64  34]]

 [[111 118 104]
  [111 118 104]
  [111 118 104]
  ...
  [ 57  69  40]
  [ 57  64  34]
  [ 57  64  34]]

 [[111 118 106]
  [111 118 106]
  [111 118 106]
  ...
  [ 57  69  40]
  [ 56  62  34]
  [ 56  62  34]]

 ...

 [[ 34  45  34]
  [ 36  47  36]
  [ 43  42  36]
  ...
  [ 46  60  52]
  [ 40  43  33]
  [ 31  34  24]]

 [[ 20  48  33]
  [ 22  50  35]
  [ 34  48  35]
  ...
  [ 46  60  52]
  [ 40  43  33]
  [ 31  34  24]]

 [[ 20  48  33]
  [ 22  50  35]
  [ 34  48  35]
  ...
  [ 46  60  52]
  [ 40  43  33]
  [ 31  34  24]]]
/Users/mohamedbasuony/Desktop/Research/create videos/240_2_Freeform_video/1150.png
[[[102 124 105]
  [102 124 105]
  [102 124 105]
  ...
  [ 52  65  39]
  [ 54  67  36]
  [ 56  69  38]]

 [[102 124 105]
  [102 124 105]
  [102 124 105]
  ...
  [ 52  65  39]
  [ 55  68  37]
  [ 56  69  38]]

 [[104 125 104]
  [104 125 104]
  [104 125 104]
  ...
  [ 57  73  46]
  [ 58  7

[[[ 96 124 109]
  [ 96 124 109]
  [102 122 110]
  ...
  [ 61  64  41]
  [ 65  62  35]
  [ 68  65  38]]

 [[ 96 124 109]
  [ 96 124 109]
  [102 122 110]
  ...
  [ 62  65  42]
  [ 68  65  38]
  [ 69  66  39]]

 [[102 123 107]
  [102 123 107]
  [106 122 109]
  ...
  [ 65  68  45]
  [ 71  68  41]
  [ 69  66  39]]

 ...

 [[ 32  51  37]
  [ 32  51  37]
  [ 32  49  40]
  ...
  [ 36  59  51]
  [ 35  46  40]
  [ 32  43  37]]

 [[ 30  51  37]
  [ 30  51  37]
  [ 30  49  40]
  ...
  [ 42  58  51]
  [ 37  41  36]
  [ 37  41  36]]

 [[ 30  51  37]
  [ 30  51  37]
  [ 30  49  40]
  ...
  [ 46  62  55]
  [ 35  39  34]
  [ 36  40  35]]]
/Users/mohamedbasuony/Desktop/Research/create videos/240_2_Freeform_video/410.png
[[[ 75 105  78]
  [ 75 105  78]
  [ 75 105  78]
  ...
  [ 41  52  33]
  [ 43  52  33]
  [ 43  52  33]]

 [[ 75 105  78]
  [ 75 105  78]
  [ 75 105  78]
  ...
  [ 42  53  34]
  [ 44  53  34]
  [ 44  53  34]]

 [[ 73 105  78]
  [ 73 105  78]
  [ 73 105  78]
  ...
  [ 40  54  34]
  [ 40  54

[[[109 117 100]
  [109 117 100]
  [111 119 102]
  ...
  [ 55  68  42]
  [ 57  66  37]
  [ 58  67  38]]

 [[109 117 100]
  [111 119 102]
  [111 119 102]
  ...
  [ 59  72  46]
  [ 60  69  40]
  [ 61  70  41]]

 [[116 117 104]
  [116 117 104]
  [116 117 104]
  ...
  [ 57  73  46]
  [ 57  69  40]
  [ 58  70  41]]

 ...

 [[ 38  45  38]
  [ 38  45  38]
  [ 48  40  35]
  ...
  [ 43  56  50]
  [ 34  43  37]
  [ 31  40  34]]

 [[ 34  47  36]
  [ 34  47  36]
  [ 45  43  34]
  ...
  [ 42  55  49]
  [ 34  43  37]
  [ 30  39  33]]

 [[ 34  47  36]
  [ 34  47  36]
  [ 45  43  34]
  ...
  [ 41  54  48]
  [ 33  42  36]
  [ 30  39  33]]]
/Users/mohamedbasuony/Desktop/Research/create videos/240_2_Freeform_video/1630.png
[[[115 127  98]
  [115 127  98]
  [115 126 100]
  ...
  [ 66  69  51]
  [ 70  66  49]
  [ 68  64  47]]

 [[115 127  98]
  [115 127  98]
  [115 126 100]
  ...
  [ 66  69  51]
  [ 70  66  49]
  [ 68  64  47]]

 [[115 124 105]
  [115 124 105]
  [115 123 106]
  ...
  [ 65  71  52]
  [ 68  6

[[[106 122 107]
  [106 122 107]
  [106 122 107]
  ...
  [ 53  69  44]
  [ 47  63  38]
  [ 50  66  41]]

 [[106 122 107]
  [106 122 107]
  [106 122 107]
  ...
  [ 53  69  44]
  [ 47  63  38]
  [ 50  66  41]]

 [[112 121 107]
  [112 121 107]
  [112 121 107]
  ...
  [ 54  70  45]
  [ 48  64  39]
  [ 50  66  41]]

 ...

 [[ 34  41  34]
  [ 35  42  35]
  [ 37  42  35]
  ...
  [ 42  57  46]
  [ 35  49  36]
  [ 30  44  31]]

 [[ 42  41  35]
  [ 42  41  35]
  [ 43  42  36]
  ...
  [ 46  55  49]
  [ 41  46  39]
  [ 34  39  32]]

 [[ 41  40  34]
  [ 41  40  34]
  [ 41  40  34]
  ...
  [ 45  54  48]
  [ 38  43  36]
  [ 34  39  32]]]
/Users/mohamedbasuony/Desktop/Research/create videos/240_2_Freeform_video/370.png
[[[106 122 102]
  [106 122 102]
  [108 122 102]
  ...
  [ 49  70  40]
  [ 49  68  38]
  [ 50  69  39]]

 [[106 122 102]
  [106 122 102]
  [108 122 102]
  ...
  [ 50  71  41]
  [ 50  69  39]
  [ 51  70  40]]

 [[110 124 104]
  [110 124 104]
  [110 124 104]
  ...
  [ 51  74  46]
  [ 50  71

[[[ 98 124 107]
  [ 98 124 107]
  [ 98 124 107]
  ...
  [ 50  72  40]
  [ 47  69  37]
  [ 44  66  34]]

 [[ 98 124 107]
  [ 98 124 107]
  [ 98 124 107]
  ...
  [ 50  72  40]
  [ 47  69  37]
  [ 44  66  34]]

 [[102 124 105]
  [102 124 105]
  [102 124 105]
  ...
  [ 50  72  40]
  [ 47  69  37]
  [ 44  66  34]]

 ...

 [[ 39  44  42]
  [ 39  44  42]
  [ 47  45  41]
  ...
  [ 39  63  53]
  [ 34  49  38]
  [ 30  45  34]]

 [[ 23  47  42]
  [ 24  48  43]
  [ 37  48  42]
  ...
  [ 40  59  50]
  [ 36  47  36]
  [ 31  42  31]]

 [[ 23  47  42]
  [ 24  48  43]
  [ 37  48  42]
  ...
  [ 39  58  49]
  [ 34  45  34]
  [ 29  40  29]]]
/Users/mohamedbasuony/Desktop/Research/create videos/240_2_Freeform_video/1680.png
[[[107 123 103]
  [107 123 103]
  [107 123 103]
  ...
  [ 54  66  37]
  [ 57  67  36]
  [ 59  69  38]]

 [[107 123 103]
  [107 123 103]
  [107 123 103]
  ...
  [ 55  67  38]
  [ 59  69  38]
  [ 61  71  40]]

 [[109 123 103]
  [109 123 103]
  [111 122 103]
  ...
  [ 55  66  40]
  [ 60  6

[[[103 120 102]
  [103 120 102]
  [107 119 104]
  ...
  [ 50  68  43]
  [ 48  66  39]
  [ 48  66  39]]

 [[103 120 102]
  [103 120 102]
  [107 119 104]
  ...
  [ 50  68  43]
  [ 49  67  40]
  [ 49  67  40]]

 [[109 118 104]
  [109 118 104]
  [109 118 106]
  ...
  [ 51  68  45]
  [ 49  67  42]
  [ 50  68  43]]

 ...

 [[ 32  47  36]
  [ 32  47  36]
  [ 36  43  36]
  ...
  [ 36  54  47]
  [ 27  43  36]
  [ 21  37  30]]

 [[ 28  47  33]
  [ 30  49  35]
  [ 32  48  35]
  ...
  [ 37  55  48]
  [ 29  42  36]
  [ 23  36  30]]

 [[ 28  47  33]
  [ 30  49  35]
  [ 32  48  35]
  ...
  [ 37  55  48]
  [ 29  42  36]
  [ 23  36  30]]]
/Users/mohamedbasuony/Desktop/Research/create videos/240_2_Freeform_video/1530.png
[[[106 123 105]
  [106 123 105]
  [106 123 105]
  ...
  [ 56  67  43]
  [ 55  66  42]
  [ 56  67  43]]

 [[106 123 105]
  [106 123 105]
  [106 123 105]
  ...
  [ 57  68  44]
  [ 55  66  42]
  [ 55  66  42]]

 [[106 123 105]
  [106 123 105]
  [106 123 105]
  ...
  [ 56  67  43]
  [ 55  6

[[[ 99 116  98]
  [100 117  99]
  [100 118  98]
  ...
  [ 62  70  46]
  [ 62  67  42]
  [ 60  65  40]]

 [[ 99 116  98]
  [100 117  99]
  [100 118  98]
  ...
  [ 62  70  46]
  [ 62  67  42]
  [ 60  65  40]]

 [[ 99 116  98]
  [100 117  99]
  [100 118  98]
  ...
  [ 60  68  44]
  [ 60  65  40]
  [ 59  64  39]]

 ...

 [[ 17  46  35]
  [ 17  46  35]
  [ 15  46  35]
  ...
  [ 30  50  47]
  [ 22  39  37]
  [ 21  38  36]]

 [[ 23  45  35]
  [ 23  45  35]
  [ 23  45  35]
  ...
  [ 30  50  47]
  [ 22  39  37]
  [ 21  38  36]]

 [[ 23  45  35]
  [ 23  45  35]
  [ 23  45  35]
  ...
  [ 33  53  50]
  [ 25  42  40]
  [ 23  40  38]]]
/Users/mohamedbasuony/Desktop/Research/create videos/240_2_Freeform_video/2370.png
[[[111 125 105]
  [111 125 105]
  [113 123 106]
  ...
  [ 61  72  46]
  [ 66  67  40]
  [ 65  66  39]]

 [[111 125 105]
  [111 125 105]
  [113 123 106]
  ...
  [ 61  72  46]
  [ 67  68  41]
  [ 65  66  39]]

 [[118 123 106]
  [118 123 106]
  [120 122 106]
  ...
  [ 61  72  46]
  [ 65  6

[[[ 99 116  98]
  [ 99 116  98]
  [ 98 119  98]
  ...
  [ 51  67  42]
  [ 43  61  34]
  [ 41  59  32]]

 [[ 99 116  98]
  [ 99 116  98]
  [ 98 119  98]
  ...
  [ 51  67  42]
  [ 43  61  34]
  [ 41  59  32]]

 [[ 99 116  98]
  [ 99 116  98]
  [ 98 119  98]
  ...
  [ 51  67  42]
  [ 43  61  34]
  [ 41  59  32]]

 ...

 [[ 34  43  31]
  [ 34  43  31]
  [ 30  44  31]
  ...
  [ 23  47  44]
  [ 19  39  36]
  [ 17  37  34]]

 [[ 34  43  31]
  [ 34  43  31]
  [ 30  44  31]
  ...
  [ 23  50  46]
  [ 22  42  39]
  [ 19  39  36]]

 [[ 34  43  31]
  [ 34  43  31]
  [ 30  44  31]
  ...
  [ 24  51  47]
  [ 26  46  43]
  [ 23  43  40]]]
/Users/mohamedbasuony/Desktop/Research/create videos/240_2_Freeform_video/2340.png
[[[110 122 107]
  [110 122 107]
  [110 122 107]
  ...
  [ 61  68  54]
  [ 60  63  45]
  [ 55  58  40]]

 [[110 122 107]
  [110 122 107]
  [110 122 107]
  ...
  [ 59  66  52]
  [ 60  63  45]
  [ 56  59  41]]

 [[110 122 107]
  [110 122 107]
  [110 122 109]
  ...
  [ 61  70  56]
  [ 59  6

[[[110 121 102]
  [110 121 102]
  [107 120 102]
  ...
  [ 60  74  45]
  [ 52  66  37]
  [ 46  60  31]]

 [[110 121 102]
  [110 121 102]
  [108 121 103]
  ...
  [ 60  74  45]
  [ 53  67  38]
  [ 47  61  32]]

 [[108 123 105]
  [107 122 104]
  [108 120 105]
  ...
  [ 57  74  44]
  [ 55  69  40]
  [ 50  64  35]]

 ...

 [[ 47  47  31]
  [ 47  47  31]
  [ 45  47  31]
  ...
  [ 46  56  55]
  [ 41  44  44]
  [ 35  38  38]]

 [[ 45  51  32]
  [ 45  51  32]
  [ 42  51  32]
  ...
  [ 50  55  55]
  [ 47  42  43]
  [ 42  37  38]]

 [[ 45  51  32]
  [ 45  51  32]
  [ 42  51  32]
  ...
  [ 48  53  53]
  [ 44  39  40]
  [ 38  33  34]]]
/Users/mohamedbasuony/Desktop/Research/create videos/240_2_Freeform_video/2180.png
[[[112 123 104]
  [112 123 104]
  [114 125 106]
  ...
  [ 50  71  41]
  [ 45  65  33]
  [ 45  65  33]]

 [[112 123 104]
  [112 123 104]
  [114 125 106]
  ...
  [ 51  72  42]
  [ 46  66  34]
  [ 46  66  34]]

 [[112 121 107]
  [112 121 107]
  [112 124 109]
  ...
  [ 53  74  44]
  [ 50  7

[[[105 121 106]
  [105 121 106]
  [107 121 106]
  ...
  [ 56  69  43]
  [ 54  64  33]
  [ 60  70  39]]

 [[105 121 106]
  [105 121 106]
  [107 121 106]
  ...
  [ 59  72  46]
  [ 57  67  36]
  [ 60  70  39]]

 [[111 120 106]
  [111 120 106]
  [113 120 106]
  ...
  [ 63  76  50]
  [ 59  69  38]
  [ 58  68  37]]

 ...

 [[ 33  41  40]
  [ 33  41  40]
  [ 27  42  38]
  ...
  [ 37  55  48]
  [ 30  46  39]
  [ 27  43  36]]

 [[ 26  45  36]
  [ 26  45  36]
  [ 22  47  34]
  ...
  [ 40  56  49]
  [ 36  45  39]
  [ 32  41  35]]

 [[ 26  45  36]
  [ 26  45  36]
  [ 22  47  34]
  ...
  [ 42  58  51]
  [ 36  45  39]
  [ 33  42  36]]]
/Users/mohamedbasuony/Desktop/Research/create videos/240_2_Freeform_video/2430.png
[[[108 123 105]
  [108 123 105]
  [108 122 107]
  ...
  [ 69  72  47]
  [ 72  70  46]
  [ 68  66  42]]

 [[108 123 105]
  [108 123 105]
  [108 122 107]
  ...
  [ 69  72  47]
  [ 72  70  46]
  [ 68  66  42]]

 [[114 122 105]
  [114 122 105]
  [117 122 105]
  ...
  [ 66  75  46]
  [ 68  7

[[[117 118 105]
  [118 119 106]
  [111 120 106]
  ...
  [ 63  75  46]
  [ 61  71  40]
  [ 55  65  34]]

 [[117 118 105]
  [118 119 106]
  [111 120 106]
  ...
  [ 63  75  46]
  [ 64  74  43]
  [ 60  70  39]]

 [[119 119 103]
  [120 120 104]
  [113 121 104]
  ...
  [ 55  67  38]
  [ 62  72  41]
  [ 66  76  45]]

 ...

 [[ 39  47  37]
  [ 36  44  34]
  [ 35  48  37]
  ...
  [ 38  58  53]
  [ 41  38  37]
  [ 33  30  29]]

 [[ 29  49  37]
  [ 26  46  34]
  [ 33  48  37]
  ...
  [ 37  57  52]
  [ 41  38  37]
  [ 35  32  31]]

 [[ 29  49  37]
  [ 26  46  34]
  [ 33  48  37]
  ...
  [ 36  56  51]
  [ 41  38  37]
  [ 35  32  31]]]
/Users/mohamedbasuony/Desktop/Research/create videos/240_2_Freeform_video/480.png
[[[107 122  99]
  [107 122  99]
  [105 121 101]
  ...
  [ 57  67  45]
  [ 54  67  43]
  [ 52  65  41]]

 [[107 122  99]
  [107 122  99]
  [105 121 101]
  ...
  [ 57  67  45]
  [ 54  67  43]
  [ 52  65  41]]

 [[107 120 102]
  [107 120 102]
  [105 120 102]
  ...
  [ 57  67  45]
  [ 54  67

[[[103 120  97]
  [103 120  97]
  [103 120  97]
  ...
  [ 66  69  51]
  [ 58  59  41]
  [ 59  60  42]]

 [[103 120  97]
  [103 120  97]
  [103 120  97]
  ...
  [ 64  67  49]
  [ 58  59  41]
  [ 59  60  42]]

 [[103 120  97]
  [103 120  97]
  [103 120  97]
  ...
  [ 63  67  46]
  [ 58  60  39]
  [ 61  63  42]]

 ...

 [[ 17  46  35]
  [ 17  46  35]
  [ 19  45  35]
  ...
  [ 33  53  50]
  [ 34  44  43]
  [ 31  41  40]]

 [[ 25  44  35]
  [ 25  44  35]
  [ 25  44  35]
  ...
  [ 37  52  48]
  [ 36  44  41]
  [ 33  41  38]]

 [[ 25  44  35]
  [ 25  44  35]
  [ 25  44  35]
  ...
  [ 37  52  48]
  [ 36  44  41]
  [ 33  41  38]]]
/Users/mohamedbasuony/Desktop/Research/create videos/240_2_Freeform_video/2620.png
[[[112 123 104]
  [112 123 104]
  [112 123 104]
  ...
  [ 61  68  38]
  [ 56  63  33]
  [ 56  63  33]]

 [[112 123 104]
  [112 123 104]
  [112 123 104]
  ...
  [ 62  69  39]
  [ 57  64  34]
  [ 56  63  33]]

 [[115 123 106]
  [115 123 106]
  [111 124 106]
  ...
  [ 57  72  41]
  [ 53  6

[[[106 121 103]
  [107 122 104]
  [110 123 105]
  ...
  [ 66  66  44]
  [ 67  63  41]
  [ 67  63  41]]

 [[106 121 103]
  [107 122 104]
  [110 123 105]
  ...
  [ 67  67  45]
  [ 67  63  41]
  [ 68  64  42]]

 [[106 121 103]
  [107 122 104]
  [110 123 105]
  ...
  [ 70  68  46]
  [ 71  64  43]
  [ 72  65  44]]

 ...

 [[ 37  47  39]
  [ 37  47  39]
  [ 50  44  39]
  ...
  [ 44  58  50]
  [ 35  49  41]
  [ 30  44  36]]

 [[ 29  50  34]
  [ 29  50  34]
  [ 31  50  34]
  ...
  [ 50  60  52]
  [ 35  49  41]
  [ 28  42  34]]

 [[ 29  50  34]
  [ 29  50  34]
  [ 31  50  34]
  ...
  [ 50  60  52]
  [ 35  49  41]
  [ 26  40  32]]]
/Users/mohamedbasuony/Desktop/Research/create videos/240_2_Freeform_video/630.png
[[[105 122 104]
  [105 122 104]
  [103 123 104]
  ...
  [ 52  68  41]
  [ 56  68  39]
  [ 55  67  38]]

 [[105 122 104]
  [105 122 104]
  [103 123 104]
  ...
  [ 54  70  43]
  [ 58  70  41]
  [ 58  70  41]]

 [[111 121 104]
  [111 121 104]
  [111 121 104]
  ...
  [ 55  71  44]
  [ 59  71

[[[109 121 108]
  [110 122 109]
  [108 122 109]
  ...
  [ 52  70  45]
  [ 49  69  44]
  [ 49  69  44]]

 [[109 121 108]
  [110 122 109]
  [108 122 109]
  ...
  [ 52  70  45]
  [ 49  69  44]
  [ 49  69  44]]

 [[116 120 106]
  [117 121 107]
  [114 121 107]
  ...
  [ 52  70  45]
  [ 48  68  43]
  [ 48  68  43]]

 ...

 [[ 41  47  37]
  [ 41  47  37]
  [ 29  49  37]
  ...
  [ 32  56  51]
  [ 26  46  41]
  [ 28  48  43]]

 [[ 38  47  35]
  [ 38  47  35]
  [ 35  49  36]
  ...
  [ 34  56  51]
  [ 28  45  41]
  [ 30  47  43]]

 [[ 38  47  35]
  [ 38  47  35]
  [ 35  49  36]
  ...
  [ 34  56  51]
  [ 28  45  41]
  [ 30  47  43]]]
/Users/mohamedbasuony/Desktop/Research/create videos/240_2_Freeform_video/2080.png
[[[110 121 102]
  [110 121 102]
  [112 123 104]
  ...
  [ 57  73  46]
  [ 53  69  42]
  [ 52  68  41]]

 [[110 121 102]
  [110 121 102]
  [112 123 104]
  ...
  [ 57  73  46]
  [ 53  69  42]
  [ 52  68  41]]

 [[110 121 102]
  [110 121 102]
  [112 123 104]
  ...
  [ 58  74  47]
  [ 54  7

[[[101 123 104]
  [102 124 105]
  [100 125 105]
  ...
  [ 49  66  48]
  [ 45  65  46]
  [ 45  65  46]]

 [[101 123 104]
  [102 124 105]
  [100 125 105]
  ...
  [ 51  68  50]
  [ 47  67  48]
  [ 47  67  48]]

 [[107 123 103]
  [108 124 104]
  [106 124 104]
  ...
  [ 51  68  50]
  [ 47  67  48]
  [ 47  67  48]]

 ...

 [[ 33  49  36]
  [ 33  49  36]
  [ 21  52  36]
  ...
  [ 36  56  51]
  [ 30  45  41]
  [ 32  47  43]]

 [[ 34  48  33]
  [ 34  48  33]
  [ 29  50  34]
  ...
  [ 38  55  51]
  [ 32  44  41]
  [ 34  46  43]]

 [[ 34  48  33]
  [ 34  48  33]
  [ 29  50  34]
  ...
  [ 38  55  51]
  [ 32  44  41]
  [ 34  46  43]]]
/Users/mohamedbasuony/Desktop/Research/create videos/240_2_Freeform_video/1770.png
[[[115 122 110]
  [115 122 110]
  [115 122 110]
  ...
  [ 58  66  40]
  [ 53  61  35]
  [ 57  65  39]]

 [[114 121 109]
  [114 121 109]
  [114 121 109]
  ...
  [ 59  67  41]
  [ 54  62  36]
  [ 57  65  39]]

 [[114 121 109]
  [114 121 109]
  [112 121 109]
  ...
  [ 60  68  42]
  [ 55  6

[[[102 123 102]
  [103 124 103]
  [103 123 104]
  ...
  [ 58  66  40]
  [ 59  64  39]
  [ 59  64  39]]

 [[102 123 102]
  [103 124 103]
  [103 123 104]
  ...
  [ 59  67  41]
  [ 60  65  40]
  [ 59  64  39]]

 [[108 122 102]
  [109 123 103]
  [105 122 104]
  ...
  [ 60  68  42]
  [ 59  67  41]
  [ 58  66  40]]

 ...

 [[ 31  48  39]
  [ 31  48  39]
  [ 33  47  39]
  ...
  [ 45  55  52]
  [ 37  47  44]
  [ 31  41  38]]

 [[ 27  51  34]
  [ 27  51  34]
  [ 25  51  34]
  ...
  [ 50  58  55]
  [ 41  46  44]
  [ 32  37  35]]

 [[ 27  51  34]
  [ 27  51  34]
  [ 25  51  34]
  ...
  [ 50  58  55]
  [ 40  45  43]
  [ 27  32  30]]]
/Users/mohamedbasuony/Desktop/Research/create videos/240_2_Freeform_video/230.png
[[[108 118 110]
  [108 118 110]
  [110 122 109]
  ...
  [ 63  69  41]
  [ 63  66  34]
  [ 70  73  41]]

 [[108 118 110]
  [108 118 110]
  [110 122 109]
  ...
  [ 64  70  42]
  [ 64  67  35]
  [ 71  74  42]]

 [[112 119 107]
  [112 119 107]
  [114 121 107]
  ...
  [ 57  71  42]
  [ 57  68

/Users/mohamedbasuony/Desktop/Research/create videos/225_2_Freeform_video
/Users/mohamedbasuony/Desktop/Research/create videos/225_2_Freeform_video/360.png
[[[154 159 157]
  [154 159 157]
  [155 160 158]
  ...
  [252 234 210]
  [254 233 212]
  [254 233 212]]

 [[154 159 157]
  [154 159 157]
  [155 160 158]
  ...
  [252 234 210]
  [254 233 212]
  [254 233 212]]

 [[154 159 157]
  [154 159 157]
  [155 160 158]
  ...
  [250 235 210]
  [252 233 212]
  [252 233 212]]

 ...

 [[ 84  86  88]
  [ 84  86  88]
  [ 84  86  88]
  ...
  [131 123 136]
  [133 124 135]
  [133 124 135]]

 [[ 87  86  88]
  [ 87  86  88]
  [ 87  86  88]
  ...
  [124 122 141]
  [129 123 140]
  [129 123 140]]

 [[ 87  86  88]
  [ 87  86  88]
  [ 87  86  88]
  ...
  [123 121 140]
  [128 122 139]
  [128 122 139]]]
/Users/mohamedbasuony/Desktop/Research/create videos/225_2_Freeform_video/200.png
[[[148 158 157]
  [148 158 157]
  [148 158 157]
  ...
  [249 233 211]
  [247 233 211]
  [247 233 211]]

 [[149 159 158]
  [149 159 1

[[[154 159 157]
  [154 159 157]
  [155 160 158]
  ...
  [252 233 212]
  [254 233 212]
  [254 233 212]]

 [[154 159 157]
  [154 159 157]
  [155 160 158]
  ...
  [252 233 212]
  [254 233 212]
  [254 233 212]]

 [[154 159 157]
  [154 159 157]
  [155 160 158]
  ...
  [252 233 212]
  [252 233 212]
  [252 233 212]]

 ...

 [[ 86  85  87]
  [ 87  86  88]
  [ 87  86  88]
  ...
  [116 115 132]
  [112 113 131]
  [112 113 131]]

 [[ 79  86  87]
  [ 80  87  88]
  [ 84  86  88]
  ...
  [113 111 130]
  [111 112 130]
  [110 111 129]]

 [[ 79  86  87]
  [ 80  87  88]
  [ 84  86  88]
  ...
  [112 110 129]
  [109 110 128]
  [109 110 128]]]
/Users/mohamedbasuony/Desktop/Research/create videos/225_2_Freeform_video/20.png
[[[147 157 154]
  [147 157 154]
  [147 157 154]
  ...
  [241 229 207]
  [237 230 207]
  [237 230 207]]

 [[147 157 154]
  [147 157 154]
  [147 157 154]
  ...
  [241 229 207]
  [237 230 207]
  [237 230 207]]

 [[147 157 154]
  [147 157 154]
  [147 157 154]
  ...
  [243 229 209]
  [239 230 

[[[156 159 157]
  [156 159 157]
  [157 160 158]
  ...
  [248 235 210]
  [250 234 212]
  [250 234 212]]

 [[156 159 157]
  [156 159 157]
  [157 160 158]
  ...
  [248 235 210]
  [250 234 212]
  [250 234 212]]

 [[156 159 157]
  [156 159 157]
  [157 160 158]
  ...
  [246 235 210]
  [248 234 212]
  [248 234 212]]

 ...

 [[ 91  85  88]
  [ 91  85  88]
  [ 91  85  88]
  ...
  [130 125 139]
  [132 124 137]
  [132 124 137]]

 [[ 89  85  88]
  [ 89  85  88]
  [ 91  85  88]
  ...
  [130 122 144]
  [134 122 142]
  [134 122 142]]

 [[ 89  85  88]
  [ 89  85  88]
  [ 91  85  88]
  ...
  [128 120 142]
  [132 120 140]
  [132 120 140]]]
/Users/mohamedbasuony/Desktop/Research/create videos/225_2_Freeform_video/90.png
[[[147 159 156]
  [148 160 157]
  [149 161 158]
  ...
  [252 233 212]
  [254 233 212]
  [254 233 212]]

 [[147 159 156]
  [148 160 157]
  [149 161 158]
  ...
  [252 233 212]
  [254 233 212]
  [254 233 212]]

 [[147 159 156]
  [148 160 157]
  [149 161 158]
  ...
  [254 232 215]
  [255 231 

[[[236 236 236]
  [236 236 236]
  [236 236 236]
  ...
  [177 174 173]
  [175 172 171]
  [174 171 170]]

 [[236 236 236]
  [236 236 236]
  [236 236 236]
  ...
  [177 174 173]
  [175 172 171]
  [175 172 171]]

 [[236 236 236]
  [236 236 236]
  [236 236 236]
  ...
  [177 174 173]
  [176 173 172]
  [175 172 171]]

 ...

 [[118 123 123]
  [118 123 123]
  [118 123 123]
  ...
  [ 98  98  98]
  [ 97  97  97]
  [ 96  96  96]]

 [[118 123 123]
  [118 123 123]
  [118 123 123]
  ...
  [ 97  97  95]
  [ 96  96  94]
  [ 95  95  93]]

 [[118 123 123]
  [118 123 123]
  [118 123 123]
  ...
  [ 97  97  95]
  [ 96  96  94]
  [ 95  95  93]]]
/Users/mohamedbasuony/Desktop/Research/create videos/320_1_Northwind_video/70.png
[[[238 238 236]
  [238 238 236]
  [238 238 236]
  ...
  [174 174 174]
  [174 174 174]
  [174 174 174]]

 [[238 238 236]
  [238 238 236]
  [238 238 236]
  ...
  [174 174 174]
  [174 174 174]
  [174 174 174]]

 [[238 238 236]
  [238 238 236]
  [238 238 236]
  ...
  [174 174 174]
  [174 174

[[[236 234 230]
  [236 234 230]
  [236 234 230]
  ...
  [172 172 170]
  [171 171 169]
  [171 171 169]]

 [[236 234 230]
  [236 234 230]
  [236 234 230]
  ...
  [172 172 170]
  [171 171 169]
  [171 171 169]]

 [[236 234 230]
  [236 234 230]
  [236 234 230]
  ...
  [172 172 170]
  [171 171 169]
  [171 171 169]]

 ...

 [[120 123 123]
  [120 123 123]
  [120 123 123]
  ...
  [104  94  96]
  [105  95  97]
  [105  95  97]]

 [[120 123 123]
  [120 123 123]
  [120 123 123]
  ...
  [104  94  96]
  [105  95  97]
  [105  95  97]]

 [[120 123 123]
  [120 123 123]
  [120 123 123]
  ...
  [104  94  96]
  [105  95  97]
  [105  95  97]]]
/Users/mohamedbasuony/Desktop/Research/create videos/320_1_Northwind_video/260.png
[[[234 234 234]
  [235 235 235]
  [235 235 235]
  ...
  [174 168 171]
  [174 168 171]
  [174 168 171]]

 [[234 234 234]
  [235 235 235]
  [235 235 235]
  ...
  [175 169 172]
  [176 170 173]
  [176 170 173]]

 [[234 234 234]
  [235 235 235]
  [235 235 235]
  ...
  [175 170 171]
  [176 17

[[[234 234 232]
  [234 234 232]
  [234 234 232]
  ...
  [174 171 172]
  [174 171 172]
  [174 171 172]]

 [[232 232 230]
  [232 232 230]
  [232 232 230]
  ...
  [174 171 172]
  [174 171 172]
  [174 171 172]]

 [[232 232 230]
  [232 232 230]
  [232 232 230]
  ...
  [174 171 172]
  [174 171 172]
  [174 171 172]]

 ...

 [[123 126 126]
  [123 126 126]
  [123 126 126]
  ...
  [100  99 101]
  [100  99 101]
  [ 98  97  99]]

 [[122 125 125]
  [122 125 125]
  [122 125 125]
  ...
  [100  99 101]
  [100  99 101]
  [ 98  97  99]]

 [[122 125 125]
  [122 125 125]
  [122 125 125]
  ...
  [100  99 101]
  [100  99 101]
  [ 97  96  98]]]
/Users/mohamedbasuony/Desktop/Research/create videos/320_1_Northwind_video/530.png
[[[242 237 238]
  [242 237 238]
  [242 237 238]
  ...
  [173 173 171]
  [173 173 171]
  [172 172 170]]

 [[242 237 238]
  [242 237 238]
  [242 237 238]
  ...
  [173 173 171]
  [173 173 171]
  [172 172 170]]

 [[242 237 238]
  [242 237 238]
  [242 237 238]
  ...
  [173 173 171]
  [173 17

[[[231 231 231]
  [231 231 231]
  [231 231 231]
  ...
  [170 170 168]
  [168 168 166]
  [168 168 166]]

 [[231 231 231]
  [231 231 231]
  [231 231 231]
  ...
  [170 170 168]
  [168 168 166]
  [168 168 166]]

 [[231 231 231]
  [231 231 231]
  [231 231 231]
  ...
  [170 170 168]
  [168 168 166]
  [168 168 166]]

 ...

 [[123 126 126]
  [123 126 126]
  [123 126 126]
  ...
  [101  96  97]
  [102  97  98]
  [102  97  98]]

 [[123 126 126]
  [123 126 126]
  [123 126 126]
  ...
  [101  96  97]
  [102  97  98]
  [102  97  98]]

 [[123 126 126]
  [123 126 126]
  [123 126 126]
  ...
  [101  96  97]
  [102  97  98]
  [102  97  98]]]
/Users/mohamedbasuony/Desktop/Research/create videos/320_1_Northwind_video/870.png
[[[237 234 235]
  [237 234 235]
  [237 234 235]
  ...
  [168 173 173]
  [167 172 172]
  [167 172 172]]

 [[237 234 235]
  [237 234 235]
  [237 234 235]
  ...
  [168 173 173]
  [167 172 172]
  [167 172 172]]

 [[237 234 235]
  [237 234 235]
  [237 234 235]
  ...
  [168 173 173]
  [167 17

[[[239 236 235]
  [239 236 235]
  [240 237 236]
  ...
  [178 172 175]
  [178 172 175]
  [178 172 175]]

 [[239 236 235]
  [239 236 235]
  [240 237 236]
  ...
  [179 173 176]
  [179 173 176]
  [179 173 176]]

 [[239 236 235]
  [239 236 235]
  [240 237 236]
  ...
  [179 173 176]
  [179 173 176]
  [179 173 176]]

 ...

 [[126 129 129]
  [126 129 129]
  [126 129 129]
  ...
  [104  99 100]
  [104  99 100]
  [104  99 100]]

 [[125 128 128]
  [125 128 128]
  [125 128 128]
  ...
  [104  99 100]
  [104  99 100]
  [104  99 100]]

 [[125 128 128]
  [125 128 128]
  [125 128 128]
  ...
  [104  99 100]
  [104  99 100]
  [104  99 100]]]
/Users/mohamedbasuony/Desktop/Research/create videos/320_1_Northwind_video/40.png
[[[240 237 236]
  [240 237 236]
  [240 237 236]
  ...
  [171 174 174]
  [171 174 174]
  [171 174 174]]

 [[240 237 236]
  [240 237 236]
  [240 237 236]
  ...
  [171 174 174]
  [171 174 174]
  [171 174 174]]

 [[240 237 236]
  [240 237 236]
  [240 237 236]
  ...
  [171 174 172]
  [171 174

[[[234 234 234]
  [234 234 234]
  [234 234 234]
  ...
  [175 172 173]
  [175 172 173]
  [175 172 173]]

 [[234 234 234]
  [234 234 234]
  [234 234 234]
  ...
  [175 172 173]
  [175 172 173]
  [175 172 173]]

 [[234 234 234]
  [234 234 234]
  [234 234 234]
  ...
  [175 172 173]
  [175 172 173]
  [175 172 173]]

 ...

 [[129 128 130]
  [129 128 130]
  [129 128 130]
  ...
  [102  97  98]
  [101  96  97]
  [101  96  97]]

 [[129 128 130]
  [129 128 130]
  [129 128 130]
  ...
  [102  97  98]
  [101  96  97]
  [101  96  97]]

 [[129 128 130]
  [129 128 130]
  [129 128 130]
  ...
  [102  97  98]
  [101  96  97]
  [101  96  97]]]
/Users/mohamedbasuony/Desktop/Research/create videos/320_1_Northwind_video/190.png
[[[236 233 232]
  [236 233 232]
  [236 233 232]
  ...
  [169 172 172]
  [169 172 172]
  [169 172 172]]

 [[236 233 232]
  [236 233 232]
  [236 233 232]
  ...
  [169 172 172]
  [169 172 172]
  [169 172 172]]

 [[236 233 232]
  [236 233 232]
  [236 233 232]
  ...
  [169 172 172]
  [169 17

[[[151 146 145]
  [151 146 145]
  [151 146 145]
  ...
  [ 92  94  96]
  [101 103 105]
  [121 123 125]]

 [[151 146 145]
  [151 146 145]
  [151 146 145]
  ...
  [ 92  94  96]
  [101 103 105]
  [121 123 125]]

 [[151 146 145]
  [151 146 145]
  [151 146 145]
  ...
  [ 92  94  96]
  [101 103 105]
  [121 123 125]]

 ...

 [[134 125 122]
  [134 125 122]
  [134 125 122]
  ...
  [103  97  85]
  [106  98  86]
  [100  92  80]]

 [[136 127 124]
  [136 127 124]
  [136 127 124]
  ...
  [103  98  83]
  [104  99  84]
  [ 98  93  78]]

 [[136 127 124]
  [136 127 124]
  [136 127 124]
  ...
  [103  98  83]
  [104  99  84]
  [ 98  93  78]]]
/Users/mohamedbasuony/Desktop/Research/create videos/332_2_Northwind_video/990.png
[[[153 146 143]
  [153 146 143]
  [153 146 143]
  ...
  [ 79  89  88]
  [ 94 104 103]
  [117 127 126]]

 [[153 146 143]
  [153 146 143]
  [153 146 143]
  ...
  [ 79  89  88]
  [ 95 105 104]
  [117 127 126]]

 [[153 146 143]
  [153 146 143]
  [153 146 143]
  ...
  [ 80  90  89]
  [ 95 10

[[[152 144 144]
  [152 144 144]
  [152 144 144]
  ...
  [ 86  87  92]
  [105 106 111]
  [123 124 129]]

 [[152 144 144]
  [152 144 144]
  [152 144 144]
  ...
  [ 86  87  92]
  [104 105 110]
  [123 124 129]]

 [[152 144 144]
  [152 144 144]
  [152 144 144]
  ...
  [ 89  87  92]
  [107 105 110]
  [126 124 129]]

 ...

 [[137 128 125]
  [137 128 125]
  [137 128 125]
  ...
  [101  91  86]
  [101  87  85]
  [102  88  86]]

 [[137 128 125]
  [137 128 125]
  [137 128 125]
  ...
  [100  90  85]
  [101  87  85]
  [102  88  86]]

 [[137 128 125]
  [137 128 125]
  [137 128 125]
  ...
  [ 99  89  84]
  [ 99  85  83]
  [102  88  86]]]
/Users/mohamedbasuony/Desktop/Research/create videos/332_2_Northwind_video/310.png
[[[152 144 144]
  [152 144 144]
  [152 144 144]
  ...
  [ 94  97  97]
  [100 103 103]
  [125 128 128]]

 [[152 144 144]
  [152 144 144]
  [152 144 144]
  ...
  [ 94  97  97]
  [100 103 103]
  [125 128 128]]

 [[152 144 144]
  [152 144 144]
  [152 144 144]
  ...
  [ 94  97  97]
  [ 99 10

[[[155 147 147]
  [155 147 147]
  [155 147 147]
  ...
  [ 86  87  92]
  [105 106 111]
  [123 124 129]]

 [[155 147 147]
  [155 147 147]
  [155 147 147]
  ...
  [ 86  87  92]
  [104 105 110]
  [123 124 129]]

 [[155 147 147]
  [155 147 147]
  [155 147 147]
  ...
  [ 88  86  91]
  [107 105 110]
  [126 124 129]]

 ...

 [[137 128 125]
  [137 128 125]
  [137 128 125]
  ...
  [101  90  87]
  [101  86  87]
  [102  87  88]]

 [[137 128 125]
  [137 128 125]
  [137 128 125]
  ...
  [100  89  86]
  [101  86  87]
  [102  87  88]]

 [[137 128 125]
  [137 128 125]
  [137 128 125]
  ...
  [ 99  88  85]
  [ 99  84  85]
  [102  87  88]]]
/Users/mohamedbasuony/Desktop/Research/create videos/332_2_Northwind_video/320.png
[[[155 147 147]
  [155 147 147]
  [155 147 147]
  ...
  [ 91  96  96]
  [ 97 102 102]
  [121 126 126]]

 [[155 147 147]
  [155 147 147]
  [155 147 147]
  ...
  [ 91  96  96]
  [ 97 102 102]
  [121 126 126]]

 [[155 147 147]
  [155 147 147]
  [155 147 147]
  ...
  [ 91  96  96]
  [ 97 10

[[[153 146 143]
  [153 146 143]
  [153 146 143]
  ...
  [ 84  87  87]
  [102 105 105]
  [121 124 124]]

 [[153 146 143]
  [153 146 143]
  [153 146 143]
  ...
  [ 84  87  87]
  [102 105 105]
  [121 124 124]]

 [[153 146 143]
  [153 146 143]
  [153 146 143]
  ...
  [ 86  86  86]
  [104 104 104]
  [124 124 124]]

 ...

 [[137 128 125]
  [137 128 125]
  [137 128 125]
  ...
  [ 99  90  87]
  [ 99  87  87]
  [100  88  88]]

 [[137 128 125]
  [137 128 125]
  [137 128 125]
  ...
  [ 97  88  85]
  [ 98  86  86]
  [100  88  88]]

 [[137 128 125]
  [137 128 125]
  [137 128 125]
  ...
  [ 97  88  85]
  [ 97  85  85]
  [ 99  87  87]]]
/Users/mohamedbasuony/Desktop/Research/create videos/332_2_Northwind_video/80.png
[[[153 145 147]
  [153 145 147]
  [153 145 147]
  ...
  [ 88  87  89]
  [101 100 102]
  [122 121 123]]

 [[153 145 147]
  [153 145 147]
  [153 145 147]
  ...
  [ 88  87  89]
  [101 100 102]
  [122 121 123]]

 [[153 145 147]
  [153 145 147]
  [153 145 147]
  ...
  [ 89  88  90]
  [102 101

[[[152 145 142]
  [152 145 142]
  [152 145 142]
  ...
  [ 85  87  89]
  [104 106 108]
  [122 124 126]]

 [[152 145 142]
  [152 145 142]
  [152 145 142]
  ...
  [ 85  87  89]
  [104 106 108]
  [122 124 126]]

 [[152 145 142]
  [152 145 142]
  [152 145 142]
  ...
  [ 87  86  88]
  [105 104 106]
  [125 124 126]]

 ...

 [[137 128 125]
  [137 128 125]
  [137 128 125]
  ...
  [103  89  87]
  [103  86  87]
  [104  87  88]]

 [[137 128 125]
  [137 128 125]
  [137 128 125]
  ...
  [101  87  85]
  [102  85  86]
  [104  87  88]]

 [[137 128 125]
  [137 128 125]
  [137 128 125]
  ...
  [101  87  85]
  [101  84  85]
  [103  86  87]]]
/Users/mohamedbasuony/Desktop/Research/create videos/332_2_Northwind_video/90.png
[[[157 147 147]
  [157 147 147]
  [157 147 147]
  ...
  [ 86  88  90]
  [ 98 100 102]
  [119 121 123]]

 [[157 147 147]
  [157 147 147]
  [157 147 147]
  ...
  [ 86  88  90]
  [ 99 101 103]
  [120 122 124]]

 [[157 147 147]
  [157 147 147]
  [157 147 147]
  ...
  [ 86  88  90]
  [ 99 101

[[[27  4 99]
  [27  4 99]
  [29  4 99]
  ...
  [38  1 82]
  [38  1 82]
  [38  1 82]]

 [[27  4 99]
  [27  4 99]
  [29  4 99]
  ...
  [38  1 82]
  [38  1 82]
  [38  1 82]]

 [[29  4 99]
  [29  4 99]
  [31  3 99]
  ...
  [32  2 82]
  [34  2 82]
  [34  2 82]]

 ...

 [[27  0 71]
  [27  0 71]
  [30  3 69]
  ...
  [12  0 60]
  [14  0 60]
  [14  0 60]]

 [[27  0 71]
  [27  0 71]
  [30  3 69]
  ...
  [14  0 60]
  [14  0 60]
  [14  0 60]]

 [[27  0 71]
  [27  0 71]
  [30  3 69]
  ...
  [14  0 60]
  [14  0 60]
  [14  0 60]]]
/Users/mohamedbasuony/Desktop/Research/create videos/223_1_Northwind_video/560.png
[[[ 11   2 104]
  [ 11   2 104]
  [  9   2 104]
  ...
  [ 22   0  94]
  [ 24   0  92]
  [ 24   0  92]]

 [[ 11   2 104]
  [ 11   2 104]
  [  9   2 104]
  ...
  [ 22   0  94]
  [ 24   0  92]
  [ 24   0  92]]

 [[ 15   1 104]
  [ 15   1 104]
  [ 17   1 104]
  ...
  [ 16   0  92]
  [ 16   0  92]
  [ 16   0  92]]

 ...

 [[ 18   0  80]
  [ 18   0  80]
  [ 20   0  80]
  ...
  [  6   0  66]
  [  0 

[[[ 23   8  93]
  [ 23   8  93]
  [ 19   8  96]
  ...
  [ 16   0  92]
  [ 16   0  92]
  [ 16   0  92]]

 [[ 23   8  93]
  [ 23   8  93]
  [ 19   8  96]
  ...
  [ 16   0  92]
  [ 16   0  92]
  [ 16   0  92]]

 [[ 27   5  98]
  [ 27   5  98]
  [ 23   4 101]
  ...
  [ 16   0  92]
  [ 18   0  92]
  [ 18   0  92]]

 ...

 [[ 16   0  79]
  [ 16   0  79]
  [ 16   0  79]
  ...
  [  4   0  66]
  [  4   0  66]
  [  4   0  66]]

 [[ 16   0  79]
  [ 16   0  79]
  [ 16   0  79]
  ...
  [  0   0  66]
  [  0   0  66]
  [  0   0  66]]

 [[ 16   0  79]
  [ 16   0  79]
  [ 16   0  79]
  ...
  [  0   0  66]
  [  0   0  66]
  [  0   0  66]]]
/Users/mohamedbasuony/Desktop/Research/create videos/223_1_Northwind_video/300.png
[[[ 19   1 102]
  [ 21   3 104]
  [ 21   3 104]
  ...
  [ 15   0  77]
  [ 15   0  78]
  [ 15   0  78]]

 [[ 21   3 104]
  [ 21   3 104]
  [ 21   3 104]
  ...
  [ 15   0  77]
  [ 15   0  78]
  [ 15   0  78]]

 [[ 36   0 107]
  [ 36   0 107]
  [ 36   0 107]
  ...
  [  4   6  80]
  [ 12   

[[[ 33   0 100]
  [ 33   0 100]
  [ 26   0 100]
  ...
  [ 13   0  86]
  [ 13   0  86]
  [ 13   0  86]]

 [[ 33   0 100]
  [ 33   0 100]
  [ 26   0 100]
  ...
  [ 13   0  86]
  [ 13   0  86]
  [ 13   0  86]]

 [[ 30   0 100]
  [ 30   0 100]
  [ 24   0 100]
  ...
  [ 17   0  86]
  [ 17   0  86]
  [ 17   0  86]]

 ...

 [[  9   1  66]
  [  9   1  66]
  [ 11   0  66]
  ...
  [  4   0  58]
  [  2   1  58]
  [  2   1  58]]

 [[ 12   1  67]
  [ 12   1  67]
  [ 16   1  67]
  ...
  [  6   0  58]
  [  4   0  58]
  [  4   0  58]]

 [[ 12   1  67]
  [ 12   1  67]
  [ 16   1  67]
  ...
  [  6   0  58]
  [  4   0  58]
  [  4   0  58]]]
/Users/mohamedbasuony/Desktop/Research/create videos/223_1_Northwind_video/930.png
[[[24  3 93]
  [24  3 93]
  [24  3 93]
  ...
  [19  0 77]
  [21  0 75]
  [21  0 75]]

 [[24  3 93]
  [24  3 93]
  [24  3 93]
  ...
  [19  0 77]
  [21  0 75]
  [21  0 75]]

 [[24  1 96]
  [24  1 96]
  [24  1 96]
  ...
  [14  2 78]
  [16  1 78]
  [16  1 78]]

 ...

 [[ 6  3 67]
  [ 6  3 6

[[[ 13   6 101]
  [ 13   6 101]
  [ 15   5 101]
  ...
  [ 20   0  94]
  [ 22   0  94]
  [ 22   0  94]]

 [[ 13   6 101]
  [ 13   6 101]
  [ 15   5 101]
  ...
  [ 20   0  94]
  [ 22   0  94]
  [ 22   0  94]]

 [[ 13   5 104]
  [ 13   5 104]
  [ 15   4 104]
  ...
  [ 24   0  94]
  [ 26   0  94]
  [ 26   0  94]]

 ...

 [[ 18   0  79]
  [ 18   0  79]
  [ 18   0  79]
  ...
  [  9   0  67]
  [  8   0  66]
  [  8   0  66]]

 [[ 18   0  79]
  [ 18   0  79]
  [ 18   0  79]
  ...
  [ 11   0  67]
  [ 11   0  67]
  [ 10   0  66]]

 [[ 18   0  79]
  [ 18   0  79]
  [ 18   0  79]
  ...
  [ 11   0  67]
  [ 11   0  67]
  [ 11   0  67]]]
/Users/mohamedbasuony/Desktop/Research/create videos/223_1_Northwind_video/330.png
[[[ 31   0 106]
  [ 31   0 106]
  [ 31   0 106]
  ...
  [ 24   0  94]
  [ 29   0  94]
  [ 29   0  94]]

 [[ 31   0 106]
  [ 31   0 106]
  [ 31   0 106]
  ...
  [ 24   0  94]
  [ 29   0  94]
  [ 29   0  94]]

 [[ 33   0 107]
  [ 33   0 107]
  [ 33   0 106]
  ...
  [ 31   0  94]
  [ 33   

[[[33  7 91]
  [33  7 91]
  [36  7 91]
  ...
  [27  5 77]
  [30  5 77]
  [30  5 77]]

 [[33  7 91]
  [33  7 91]
  [36  7 91]
  ...
  [27  5 77]
  [30  5 77]
  [30  5 77]]

 [[36  7 91]
  [36  7 91]
  [38  6 91]
  ...
  [23  6 77]
  [25  5 77]
  [25  5 77]]

 ...

 [[20  2 69]
  [20  2 69]
  [20  2 69]
  ...
  [10  0 60]
  [10  0 60]
  [10  0 60]]

 [[20  2 69]
  [20  2 69]
  [20  2 69]
  ...
  [10  0 60]
  [10  0 60]
  [10  0 60]]

 [[20  2 69]
  [20  2 69]
  [20  2 69]
  ...
  [10  0 60]
  [10  0 60]
  [10  0 60]]]
/Users/mohamedbasuony/Desktop/Research/create videos/223_1_Northwind_video/1010.png
[[[33  2 93]
  [33  2 93]
  [33  2 93]
  ...
  [36  1 82]
  [40  1 82]
  [40  1 82]]

 [[33  2 93]
  [33  2 93]
  [33  2 93]
  ...
  [36  1 82]
  [40  1 82]
  [40  1 82]]

 [[26  2 95]
  [26  2 95]
  [26  2 95]
  ...
  [40  0 84]
  [44  0 84]
  [44  0 84]]

 ...

 [[16  1 67]
  [16  1 67]
  [14  1 67]
  ...
  [10  0 58]
  [11  0 59]
  [13  2 61]]

 [[18  0 67]
  [18  0 67]
  [16  1 67]
  ...

[[[ 41   0 101]
  [ 41   0 101]
  [ 43   0 101]
  ...
  [ 27   0  95]
  [ 30   0  89]
  [ 30   0  89]]

 [[ 41   0 101]
  [ 41   0 101]
  [ 43   0 101]
  ...
  [ 27   0  95]
  [ 30   0  89]
  [ 30   0  89]]

 [[ 42   0 105]
  [ 42   0 105]
  [ 40   0 105]
  ...
  [ 30   0  95]
  [ 32   0  89]
  [ 32   0  89]]

 ...

 [[ 11   0  79]
  [ 11   0  79]
  [ 13   0  78]
  ...
  [  8   0  65]
  [ 10   0  65]
  [ 10   0  65]]

 [[ 10   0  77]
  [ 10   0  77]
  [ 12   0  75]
  ...
  [ 10   0  65]
  [ 12   0  65]
  [ 12   0  65]]

 [[  9   0  76]
  [ 10   0  77]
  [ 12   0  75]
  ...
  [ 10   0  65]
  [ 12   0  65]
  [ 12   0  65]]]
/Users/mohamedbasuony/Desktop/Research/create videos/223_1_Northwind_video/50.png
[[[ 17   4 104]
  [ 17   4 104]
  [ 17   4 103]
  ...
  [ 27   5  77]
  [ 27   5  77]
  [ 27   5  77]]

 [[ 17   4 104]
  [ 17   4 104]
  [ 17   4 103]
  ...
  [ 27   5  77]
  [ 27   5  77]
  [ 27   5  77]]

 [[ 27   2 103]
  [ 27   2 103]
  [ 27   2 103]
  ...
  [ 30   5  77]
  [ 30   5

[[[ 20   0 101]
  [ 20   0 101]
  [ 22   0 101]
  ...
  [ 30   0  87]
  [ 30   0  87]
  [ 30   0  87]]

 [[ 20   0 101]
  [ 20   0 101]
  [ 22   0 101]
  ...
  [ 30   0  87]
  [ 30   0  87]
  [ 30   0  87]]

 [[ 18   0 101]
  [ 18   0 101]
  [ 20   0 101]
  ...
  [ 27   0  87]
  [ 27   0  87]
  [ 27   0  87]]

 ...

 [[ 23   1  73]
  [ 23   1  73]
  [ 21   1  73]
  ...
  [ 12   0  60]
  [ 12   0  60]
  [ 12   0  60]]

 [[ 26   1  73]
  [ 26   1  73]
  [ 23   1  73]
  ...
  [ 12   0  60]
  [ 12   0  60]
  [ 12   0  60]]

 [[ 26   1  73]
  [ 26   1  73]
  [ 23   1  73]
  ...
  [ 12   0  60]
  [ 12   0  60]
  [ 12   0  60]]]
/Users/mohamedbasuony/Desktop/Research/create videos/232_1_Freeform_video
/Users/mohamedbasuony/Desktop/Research/create videos/232_1_Freeform_video/1810.png
[[[180 199 217]
  [181 200 218]
  [181 200 218]
  ...
  [185 196 211]
  [184 195 210]
  [184 195 210]]

 [[180 199 217]
  [181 200 218]
  [181 200 218]
  ...
  [185 196 211]
  [184 195 210]
  [184 195 210]]

 [[18

[[[156 181 200]
  [157 182 201]
  [159 182 203]
  ...
  [180 182 198]
  [178 182 198]
  [177 181 197]]

 [[156 181 200]
  [157 182 201]
  [159 182 203]
  ...
  [179 181 197]
  [177 181 197]
  [176 180 196]]

 [[159 184 198]
  [160 185 199]
  [162 183 201]
  ...
  [178 182 198]
  [176 182 198]
  [175 181 197]]

 ...

 [[ 72  83 104]
  [ 72  83 104]
  [ 72  83 104]
  ...
  [ 41  28  32]
  [ 43  25  35]
  [ 44  26  36]]

 [[ 72  83 104]
  [ 72  83 104]
  [ 72  83 104]
  ...
  [ 41  27  34]
  [ 41  26  35]
  [ 41  26  35]]

 [[ 72  83 104]
  [ 72  83 104]
  [ 72  83 104]
  ...
  [ 41  27  34]
  [ 41  26  35]
  [ 41  26  35]]]
/Users/mohamedbasuony/Desktop/Research/create videos/232_1_Freeform_video/1620.png
[[[185 201 220]
  [185 201 220]
  [185 201 220]
  ...
  [191 197 213]
  [188 198 210]
  [187 197 209]]

 [[183 199 218]
  [183 199 218]
  [185 201 220]
  ...
  [191 197 213]
  [188 198 210]
  [187 197 209]]

 [[179 200 218]
  [179 200 218]
  [181 202 220]
  ...
  [193 199 215]
  [189 19

[[[209 228 246]
  [209 228 246]
  [207 228 246]
  ...
  [216 231 247]
  [216 231 247]
  [216 231 247]]

 [[209 228 246]
  [209 228 246]
  [207 228 246]
  ...
  [216 231 247]
  [216 231 247]
  [216 231 247]]

 [[213 227 246]
  [213 227 246]
  [213 227 246]
  ...
  [218 231 247]
  [218 231 247]
  [218 231 247]]

 ...

 [[105 115 141]
  [106 116 142]
  [107 117 143]
  ...
  [ 94  80  92]
  [ 99  83  95]
  [101  85  97]]

 [[105 115 141]
  [107 117 143]
  [107 117 143]
  ...
  [ 94  80  92]
  [100  84  96]
  [104  88 100]]

 [[105 115 141]
  [107 117 143]
  [107 117 143]
  ...
  [ 94  80  92]
  [100  84  96]
  [105  89 101]]]
/Users/mohamedbasuony/Desktop/Research/create videos/232_1_Freeform_video/1180.png
[[[206 227 240]
  [206 227 240]
  [204 227 240]
  ...
  [214 224 241]
  [214 224 241]
  [214 224 241]]

 [[206 227 240]
  [206 227 240]
  [204 227 240]
  ...
  [214 224 241]
  [214 224 241]
  [214 224 241]]

 [[206 227 240]
  [206 227 240]
  [204 227 240]
  ...
  [211 225 239]
  [211 22

[[[182 197 218]
  [182 197 218]
  [182 197 218]
  ...
  [187 198 213]
  [187 198 213]
  [187 198 213]]

 [[182 197 218]
  [182 197 218]
  [182 197 218]
  ...
  [187 198 213]
  [187 198 213]
  [187 198 213]]

 [[180 198 218]
  [180 198 218]
  [180 198 218]
  ...
  [187 198 213]
  [187 198 213]
  [187 198 213]]

 ...

 [[ 84  94 120]
  [ 84  94 120]
  [ 84  94 120]
  ...
  [ 68  58  71]
  [ 68  58  71]
  [ 68  58  71]]

 [[ 84  94 120]
  [ 84  94 120]
  [ 84  94 120]
  ...
  [ 68  58  71]
  [ 68  58  71]
  [ 68  58  71]]

 [[ 84  94 120]
  [ 84  94 120]
  [ 84  94 120]
  ...
  [ 68  58  71]
  [ 68  58  71]
  [ 68  58  71]]]
/Users/mohamedbasuony/Desktop/Research/create videos/232_1_Freeform_video/1020.png
[[[192 210 237]
  [192 210 237]
  [192 210 237]
  ...
  [197 210 226]
  [197 210 226]
  [197 210 226]]

 [[192 210 237]
  [192 210 237]
  [192 210 237]
  ...
  [197 210 226]
  [197 210 226]
  [197 210 226]]

 [[189 210 236]
  [189 210 236]
  [189 210 236]
  ...
  [197 210 226]
  [197 21

[[[208 229 242]
  [209 230 243]
  [209 229 244]
  ...
  [216 228 240]
  [219 226 239]
  [218 225 238]]

 [[208 229 242]
  [209 230 243]
  [209 229 244]
  ...
  [216 228 240]
  [219 226 239]
  [218 225 238]]

 [[210 227 243]
  [211 228 244]
  [211 227 246]
  ...
  [214 229 240]
  [217 227 239]
  [216 226 238]]

 ...

 [[106 117 140]
  [107 118 141]
  [109 117 141]
  ...
  [111  98 112]
  [111  96 110]
  [111  96 110]]

 [[106 117 140]
  [107 118 141]
  [109 117 141]
  ...
  [102 100 112]
  [105  97 110]
  [105  97 110]]

 [[106 117 140]
  [107 118 141]
  [109 117 141]
  ...
  [102 100 112]
  [105  97 110]
  [105  97 110]]]
/Users/mohamedbasuony/Desktop/Research/create videos/232_1_Freeform_video/1330.png
[[[205 226 244]
  [206 227 245]
  [206 227 245]
  ...
  [220 227 240]
  [220 227 240]
  [219 226 239]]

 [[205 226 244]
  [206 227 245]
  [206 227 245]
  ...
  [220 227 240]
  [220 227 240]
  [219 226 239]]

 [[209 225 244]
  [210 226 245]
  [210 226 245]
  ...
  [218 228 240]
  [218 22

[[[178 205 224]
  [178 205 224]
  [182 205 224]
  ...
  [187 204 220]
  [184 204 219]
  [184 204 219]]

 [[178 205 224]
  [178 205 224]
  [182 205 224]
  ...
  [187 204 220]
  [184 204 219]
  [184 204 219]]

 [[180 205 224]
  [180 205 224]
  [184 204 224]
  ...
  [187 204 220]
  [184 204 219]
  [184 204 219]]

 ...

 [[ 82  98 117]
  [ 82  98 117]
  [ 82  98 117]
  ...
  [ 74  66  79]
  [ 78  68  81]
  [ 78  68  81]]

 [[ 74 100 117]
  [ 74 100 117]
  [ 76 100 117]
  ...
  [ 74  66  79]
  [ 77  67  80]
  [ 78  68  81]]

 [[ 74 100 117]
  [ 74 100 117]
  [ 76 100 117]
  ...
  [ 74  66  79]
  [ 78  68  81]
  [ 79  69  82]]]
/Users/mohamedbasuony/Desktop/Research/create videos/232_1_Freeform_video/2160.png
[[[187 197 223]
  [190 200 226]
  [190 200 226]
  ...
  [184 197 213]
  [185 195 212]
  [184 194 211]]

 [[186 196 222]
  [189 199 225]
  [190 200 226]
  ...
  [185 198 214]
  [187 197 214]
  [186 196 213]]

 [[182 197 220]
  [183 198 221]
  [185 199 225]
  ...
  [183 198 214]
  [184 19

[[[177 195 217]
  [178 196 218]
  [178 196 218]
  ...
  [186 197 212]
  [183 197 211]
  [183 197 211]]

 [[177 195 217]
  [178 196 218]
  [178 196 218]
  ...
  [186 197 212]
  [183 197 211]
  [183 197 211]]

 [[177 195 217]
  [178 196 218]
  [178 196 218]
  ...
  [186 197 212]
  [183 197 211]
  [183 197 211]]

 ...

 [[ 81  93 119]
  [ 81  93 119]
  [ 82  94 120]
  ...
  [ 77  54  60]
  [ 82  57  63]
  [ 84  59  65]]

 [[ 81  93 119]
  [ 81  93 119]
  [ 82  94 120]
  ...
  [ 78  53  59]
  [ 82  57  63]
  [ 85  60  66]]

 [[ 81  93 119]
  [ 81  93 119]
  [ 82  94 120]
  ...
  [ 78  53  59]
  [ 81  56  62]
  [ 85  60  66]]]
/Users/mohamedbasuony/Desktop/Research/create videos/232_1_Freeform_video/1450.png
[[[199 226 245]
  [199 226 245]
  [199 226 245]
  ...
  [216 227 242]
  [220 225 243]
  [220 225 243]]

 [[199 226 245]
  [199 226 245]
  [199 226 245]
  ...
  [216 227 242]
  [220 225 243]
  [220 225 243]]

 [[203 226 245]
  [203 226 245]
  [206 226 246]
  ...
  [218 226 243]
  [222 22

[[[206 226 246]
  [207 227 247]
  [207 230 249]
  ...
  [225 227 243]
  [225 227 243]
  [225 227 243]]

 [[206 226 246]
  [207 227 247]
  [207 230 249]
  ...
  [225 227 243]
  [225 227 243]
  [225 227 243]]

 [[210 225 246]
  [211 226 247]
  [207 230 249]
  ...
  [221 227 243]
  [221 227 243]
  [221 227 243]]

 ...

 [[111 119 141]
  [111 119 141]
  [111 119 141]
  ...
  [102  90  97]
  [108  96 103]
  [110  98 105]]

 [[110 118 140]
  [110 118 140]
  [108 119 140]
  ...
  [103  91  98]
  [108  96 103]
  [110  98 105]]

 [[110 118 140]
  [110 118 140]
  [108 119 140]
  ...
  [103  91  98]
  [108  96 103]
  [110  98 105]]]
/Users/mohamedbasuony/Desktop/Research/create videos/232_1_Freeform_video/2370.png
[[[182 197 220]
  [182 197 220]
  [182 197 220]
  ...
  [181 197 211]
  [181 197 211]
  [181 197 211]]

 [[182 197 220]
  [182 197 220]
  [182 197 220]
  ...
  [181 197 211]
  [181 197 211]
  [181 197 211]]

 [[181 196 219]
  [181 196 219]
  [182 197 220]
  ...
  [179 197 211]
  [179 19

[[[175 192 208]
  [175 192 208]
  [176 192 211]
  ...
  [182 191 206]
  [182 191 206]
  [182 191 206]]

 [[175 192 208]
  [175 192 208]
  [176 192 211]
  ...
  [182 191 206]
  [182 191 206]
  [182 191 206]]

 [[173 193 208]
  [173 193 208]
  [176 192 211]
  ...
  [186 190 206]
  [186 190 206]
  [186 190 206]]

 ...

 [[ 77  88 111]
  [ 77  88 111]
  [ 77  88 111]
  ...
  [ 79  65  84]
  [ 76  68  83]
  [ 76  68  83]]

 [[ 77  88 111]
  [ 77  88 111]
  [ 75  88 111]
  ...
  [ 79  65  84]
  [ 76  68  83]
  [ 76  68  83]]

 [[ 77  88 111]
  [ 77  88 111]
  [ 75  88 111]
  ...
  [ 79  65  84]
  [ 76  68  83]
  [ 76  68  83]]]
/Users/mohamedbasuony/Desktop/Research/create videos/232_1_Freeform_video/3260.png
[[[175 195 217]
  [176 196 218]
  [176 196 218]
  ...
  [187 196 211]
  [187 197 209]
  [187 197 209]]

 [[175 195 217]
  [176 196 218]
  [176 196 218]
  ...
  [187 196 211]
  [187 197 209]
  [187 197 209]]

 [[175 195 217]
  [176 196 218]
  [176 196 218]
  ...
  [187 196 211]
  [187 19

[[[163 182 200]
  [164 183 201]
  [166 181 202]
  ...
  [172 178 194]
  [170 179 194]
  [170 179 194]]

 [[163 182 200]
  [164 183 201]
  [166 181 202]
  ...
  [172 178 194]
  [170 179 194]
  [170 179 194]]

 [[163 184 197]
  [164 185 198]
  [166 183 199]
  ...
  [170 179 194]
  [168 179 194]
  [168 179 194]]

 ...

 [[ 67  82 103]
  [ 67  82 103]
  [ 67  82 103]
  ...
  [ 42  29  33]
  [ 42  29  33]
  [ 42  29  33]]

 [[ 69  82 103]
  [ 69  82 103]
  [ 69  82 103]
  ...
  [ 42  29  33]
  [ 42  29  33]
  [ 42  29  33]]

 [[ 69  82 103]
  [ 69  82 103]
  [ 69  82 103]
  ...
  [ 42  29  33]
  [ 42  29  33]
  [ 42  29  33]]]
/Users/mohamedbasuony/Desktop/Research/create videos/232_1_Freeform_video/2960.png
[[[166 185 203]
  [166 185 203]
  [166 185 203]
  ...
  [172 183 198]
  [172 183 198]
  [172 183 198]]

 [[166 185 203]
  [166 185 203]
  [166 185 203]
  ...
  [172 183 198]
  [172 183 198]
  [172 183 198]]

 [[166 185 203]
  [166 185 203]
  [166 185 203]
  ...
  [172 183 198]
  [172 18

[[[178 196 218]
  [178 196 218]
  [178 196 218]
  ...
  [188 195 208]
  [186 193 206]
  [186 193 206]]

 [[178 196 218]
  [178 196 218]
  [178 196 218]
  ...
  [188 195 208]
  [188 195 208]
  [188 195 208]]

 [[178 196 218]
  [178 196 218]
  [178 196 218]
  ...
  [190 197 210]
  [190 197 210]
  [189 196 209]]

 ...

 [[ 82  89 116]
  [ 82  89 116]
  [ 83  90 117]
  ...
  [ 81  64  72]
  [ 84  67  75]
  [ 84  67  75]]

 [[ 84  89 116]
  [ 84  89 116]
  [ 85  90 117]
  ...
  [ 81  64  72]
  [ 83  66  74]
  [ 83  66  74]]

 [[ 84  89 116]
  [ 84  89 116]
  [ 85  90 117]
  ...
  [ 81  64  72]
  [ 83  66  74]
  [ 83  66  74]]]
/Users/mohamedbasuony/Desktop/Research/create videos/232_1_Freeform_video/2150.png
[[[165 200 219]
  [165 200 219]
  [171 197 221]
  ...
  [178 196 210]
  [180 194 208]
  [179 193 207]]

 [[165 200 219]
  [165 200 219]
  [171 197 221]
  ...
  [180 198 212]
  [183 197 211]
  [182 196 210]]

 [[173 198 219]
  [173 198 219]
  [177 196 221]
  ...
  [179 200 213]
  [181 19

[[[172 189 214]
  [172 189 214]
  [172 189 214]
  ...
  [176 191 200]
  [176 191 200]
  [176 191 200]]

 [[172 189 214]
  [172 189 214]
  [172 189 214]
  ...
  [176 191 200]
  [176 191 200]
  [176 191 200]]

 [[170 189 214]
  [170 189 214]
  [170 189 214]
  ...
  [176 191 200]
  [176 191 200]
  [176 191 200]]

 ...

 [[ 74  80 118]
  [ 74  80 118]
  [ 74  80 118]
  ...
  [ 35  35 109]
  [ 36  39 105]
  [ 38  41 107]]

 [[ 72  76 119]
  [ 72  76 119]
  [ 72  76 119]
  ...
  [ 29  29 103]
  [ 30  33  99]
  [ 31  34 100]]

 [[ 71  75 118]
  [ 71  75 118]
  [ 71  75 118]
  ...
  [ 27  27 101]
  [ 27  30  96]
  [ 28  31  97]]]
/Users/mohamedbasuony/Desktop/Research/create videos/232_1_Freeform_video/1300.png
[[[210 225 246]
  [211 226 247]
  [213 226 247]
  ...
  [222 227 238]
  [219 226 239]
  [219 226 239]]

 [[210 225 246]
  [211 226 247]
  [213 226 247]
  ...
  [222 227 238]
  [219 226 239]
  [219 226 239]]

 [[210 225 246]
  [211 226 247]
  [213 226 247]
  ...
  [216 228 240]
  [213 22

[[[175 199 216]
  [175 199 216]
  [175 199 216]
  ...
  [177 199 207]
  [177 199 207]
  [177 199 207]]

 [[175 199 216]
  [175 199 216]
  [175 199 216]
  ...
  [177 199 207]
  [177 199 207]
  [177 199 207]]

 [[175 199 216]
  [175 199 216]
  [177 198 216]
  ...
  [179 198 207]
  [179 198 207]
  [179 198 207]]

 ...

 [[ 92  93 118]
  [ 92  93 118]
  [ 90  93 118]
  ...
  [ 52  28  42]
  [ 52  28  42]
  [ 52  28  42]]

 [[ 87  93 117]
  [ 87  93 117]
  [ 85  93 117]
  ...
  [ 52  27  43]
  [ 52  27  43]
  [ 52  27  43]]

 [[ 87  93 117]
  [ 87  93 117]
  [ 85  93 117]
  ...
  [ 50  25  41]
  [ 50  25  41]
  [ 50  25  41]]]
/Users/mohamedbasuony/Desktop/Research/create videos/232_1_Freeform_video/1950.png
[[[199 212 235]
  [199 212 235]
  [197 212 235]
  ...
  [201 213 232]
  [201 213 232]
  [201 213 232]]

 [[199 212 235]
  [199 212 235]
  [197 212 235]
  ...
  [201 213 232]
  [201 213 232]
  [201 213 232]]

 [[199 212 235]
  [199 212 235]
  [197 212 235]
  ...
  [201 213 232]
  [201 21

[[[203 229 246]
  [203 229 246]
  [203 229 246]
  ...
  [220 228 237]
  [217 229 234]
  [216 228 233]]

 [[203 229 246]
  [203 229 246]
  [203 229 246]
  ...
  [220 228 237]
  [217 229 234]
  [216 228 233]]

 [[209 228 246]
  [209 228 246]
  [209 228 246]
  ...
  [220 227 238]
  [217 228 236]
  [216 227 235]]

 ...

 [[110 116 138]
  [110 116 138]
  [110 116 138]
  ...
  [100  98 117]
  [100  98 117]
  [100  98 117]]

 [[112 115 138]
  [112 115 138]
  [110 116 138]
  ...
  [ 97  98 116]
  [ 97  98 116]
  [ 97  98 116]]

 [[111 114 137]
  [111 114 137]
  [109 115 137]
  ...
  [ 96  97 115]
  [ 96  97 115]
  [ 96  97 115]]]
/Users/mohamedbasuony/Desktop/Research/create videos/232_1_Freeform_video/2080.png
[[[173 197 221]
  [173 197 221]
  [173 197 221]
  ...
  [182 197 213]
  [182 197 213]
  [182 197 213]]

 [[173 197 221]
  [173 197 221]
  [173 197 221]
  ...
  [182 197 213]
  [182 197 213]
  [182 197 213]]

 [[177 196 221]
  [177 196 221]
  [177 196 221]
  ...
  [183 199 213]
  [183 19

[[[173 200 214]
  [173 200 214]
  [173 200 214]
  ...
  [188 196 213]
  [188 196 213]
  [188 196 213]]

 [[172 199 213]
  [172 199 213]
  [172 199 213]
  ...
  [189 197 214]
  [188 196 213]
  [188 196 213]]

 [[170 199 213]
  [170 199 213]
  [170 199 213]
  ...
  [188 196 213]
  [188 196 213]
  [188 196 213]]

 ...

 [[ 81  94 117]
  [ 81  94 117]
  [ 81  94 117]
  ...
  [ 90  81  92]
  [ 90  81  92]
  [ 90  81  92]]

 [[ 81  94 117]
  [ 81  94 117]
  [ 81  94 117]
  ...
  [ 90  81  92]
  [ 90  81  92]
  [ 90  81  92]]

 [[ 81  94 117]
  [ 81  94 117]
  [ 81  94 117]
  ...
  [ 90  81  92]
  [ 90  81  92]
  [ 90  81  92]]]
/Users/mohamedbasuony/Desktop/Research/create videos/232_1_Freeform_video/3370.png
[[[173 196 215]
  [173 196 215]
  [176 196 216]
  ...
  [194 193 210]
  [194 193 210]
  [194 193 210]]

 [[173 196 215]
  [173 196 215]
  [176 196 216]
  ...
  [194 193 210]
  [194 193 210]
  [194 193 210]]

 [[173 196 215]
  [173 196 215]
  [174 197 216]
  ...
  [187 196 211]
  [187 19

[[[176 199 220]
  [176 199 220]
  [176 199 220]
  ...
  [184 200 207]
  [182 200 207]
  [182 200 207]]

 [[176 199 220]
  [176 199 220]
  [176 199 220]
  ...
  [184 200 207]
  [182 200 207]
  [182 200 207]]

 [[174 199 220]
  [174 199 220]
  [177 200 221]
  ...
  [182 200 207]
  [180 200 207]
  [180 200 207]]

 ...

 [[ 83  94 115]
  [ 83  94 115]
  [ 85  93 115]
  ...
  [ 64  59  73]
  [ 64  59  73]
  [ 64  59  73]]

 [[ 81  94 115]
  [ 81  94 115]
  [ 83  94 115]
  ...
  [ 64  59  73]
  [ 64  59  73]
  [ 64  59  73]]

 [[ 81  94 115]
  [ 81  94 115]
  [ 83  94 115]
  ...
  [ 64  59  73]
  [ 64  59  73]
  [ 64  59  73]]]
/Users/mohamedbasuony/Desktop/Research/create videos/232_1_Freeform_video/0.png
[[[173 191 211]
  [173 191 211]
  [173 191 211]
  ...
  [183 193 205]
  [183 193 205]
  [182 192 204]]

 [[173 191 211]
  [173 191 211]
  [173 191 211]
  ...
  [183 193 205]
  [183 193 205]
  [182 192 204]]

 [[173 191 211]
  [173 191 211]
  [173 191 211]
  ...
  [183 193 205]
  [183 193 2